Server:
    Host: ""
    Port: 2333
    SessionSecretString: ""

MongoDB:
    Host: "localhost"
    Port: 27017
    UserName: ""
    Password: 
    DbName: ""

Redis:
    Host: "localhost"
    Port: 6379
    Password: 
    DB: 0