version: "3.3"

services:

  redis:
    image: redis:7
    container_name: passport_redis
    restart: always
    hostname: redis
    ports:
      - "6378:6379"

  mongo:
    image: mongo:4
    container_name: passport_mongo
    environment:
      - MONGO_INITDB_DATABASE=my_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27018:27017"

  passport:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passport_server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
